//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promeet_Booking_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int RoomId { get; set; }
        public int UserId { get; set; }
        public bool AC { get; set; }
        public bool Projector { get; set; }
        public bool CoffeeFilter { get; set; }
        public bool WaterBottles { get; set; }
        public bool Mic { get; set; }
        public bool Speaker { get; set; }
        public bool System { get; set; }
        public bool Podium { get; set; }
        public bool WiFi { get; set; }
        public bool WhiteBoard { get; set; }
        public decimal Price { get; set; }
        public string Location { get; set; }
        public int CapacityOfRoom { get; set; }
        public bool Availability { get; set; }
        public string RoomName { get; set; }
        public bool IsRoomBooked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual User User { get; set; }
    }
}
